# Generated by Django 3.0.7 on 2020-06-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heroname', models.CharField(max_length=100)),
                ('realname', models.CharField(max_length=100)),
                ('superpower', models.CharField(max_length=100)),
                ('weapon', models.CharField(max_length=100)),
                ('weakness', models.CharField(max_length=100)),
            ],
        ),
    ]
