# Generated by Django 3.0.7 on 2020-06-26 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('villain', models.CharField(choices=[('Cheetah', 'Cheetah'), ('Lex Luther', 'Lex Luther'), ('Green Gobblin', 'Green Gobblin'), ('Joker', 'Joker'), ('Mystic', 'Mystic')], default='Cheetah', max_length=50)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Hero')),
            ],
        ),
    ]
