# Generated by Django 3.0.7 on 2020-06-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200626_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='powers',
            field=models.ManyToManyField(to='main_app.Power'),
        ),
    ]
